DROP TABLE IF EXISTS song;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS artist;
DROP TABLE IF EXISTS genre;
DROP SEQUENCE IF EXISTS song_id_seq;
DROP SEQUENCE IF EXISTS album_id_seq;
DROP SEQUENCE IF EXISTS artist_id_seq;
DROP SEQUENCE IF EXISTS genre_id_seq;